<?php

namespace Database\Seeders;

use App\Models\Company;
use App\Models\User;
use Illuminate\Database\Seeder;

class CompanySeeder extends Seeder
{
    public function run(): void
    {
        $creatorId = User::where('email', 'admin@pil.com')->value('id')
            ?? User::query()->value('id')
            ?? 1;

        $companies = [
            [
                'company_type' => 'empresa_institucional',
                'name' => 'Distribuidora Andina SRL',
                'nit' => '900000001',
                'email' => 'contacto@andina.com',
                'phone' => '70010001',
                'address' => 'Av. Busch 1234',
                'city' => 'La Paz',
                'owner_first_name' => 'Marco',
                'owner_last_name_paterno' => 'Rojas',
                'owner_last_name_materno' => 'Lopez',
            ],
            [
                'company_type' => 'empresa_institucional',
                'name' => 'Lacteos Altiplano SA',
                'nit' => '900000002',
                'email' => 'ventas@altiplano.bo',
                'phone' => '70010002',
                'address' => 'Av. 6 de Marzo 210',
                'city' => 'El Alto',
                'owner_first_name' => 'Lucia',
                'owner_last_name_paterno' => 'Quispe',
                'owner_last_name_materno' => 'Huanca',
            ],
            [
                'company_type' => 'empresa_institucional',
                'name' => 'Supermercados Cordillera',
                'nit' => '900000003',
                'email' => 'compras@cordillera.bo',
                'phone' => '70010003',
                'address' => 'Av. Costanera 455',
                'city' => 'La Paz',
                'owner_first_name' => 'Ramiro',
                'owner_last_name_paterno' => 'Aguilar',
                'owner_last_name_materno' => 'Soto',
            ],
            [
                'company_type' => 'empresa_institucional',
                'name' => 'Hospital Central La Paz',
                'nit' => '900000004',
                'email' => 'compras@hclp.bo',
                'phone' => '70010004',
                'address' => 'C. Bueno 789',
                'city' => 'La Paz',
                'owner_first_name' => 'Claudia',
                'owner_last_name_paterno' => 'Fernandez',
                'owner_last_name_materno' => 'Diaz',
            ],
            [
                'company_type' => 'empresa_institucional',
                'name' => 'Catering Delicias SRL',
                'nit' => '900000005',
                'email' => 'catering@delicias.bo',
                'phone' => '70010005',
                'address' => 'Av. America 1020',
                'city' => 'La Paz',
                'owner_first_name' => 'Paola',
                'owner_last_name_paterno' => 'Gonzales',
                'owner_last_name_materno' => 'Salazar',
            ],
            [
                'company_type' => 'empresa_institucional',
                'name' => 'Hotel Mirador Andino',
                'nit' => '900000006',
                'email' => 'compras@mirador.bo',
                'phone' => '70010006',
                'address' => 'Av. Naciones Unidas 350',
                'city' => 'El Alto',
                'owner_first_name' => 'Gustavo',
                'owner_last_name_paterno' => 'Rivera',
                'owner_last_name_materno' => 'Paredes',
            ],
            [
                'company_type' => 'empresa_institucional',
                'name' => 'Restaurante Sabores del Valle',
                'nit' => '900000007',
                'email' => 'chef@saboresvalle.bo',
                'phone' => '70010007',
                'address' => 'C. Mercado 560',
                'city' => 'La Paz',
                'owner_first_name' => 'Emilio',
                'owner_last_name_paterno' => 'Mercado',
                'owner_last_name_materno' => 'Vega',
            ],
            [
                'company_type' => 'empresa_institucional',
                'name' => 'Colegio San Martin',
                'nit' => '900000008',
                'email' => 'admin@sanmartin.edu.bo',
                'phone' => '70010008',
                'address' => 'Av. Arce 321',
                'city' => 'El Alto',
                'owner_first_name' => 'Rosa',
                'owner_last_name_paterno' => 'Maldonado',
                'owner_last_name_materno' => 'Tapia',
            ],
            [
                'company_type' => 'empresa_institucional',
                'name' => 'Fabrica Dulce Nieve',
                'nit' => '900000009',
                'email' => 'contacto@dulcenieve.bo',
                'phone' => '70010009',
                'address' => 'Parque Industrial 12',
                'city' => 'La Paz',
                'owner_first_name' => 'Miguel',
                'owner_last_name_paterno' => 'Suarez',
                'owner_last_name_materno' => 'Quiroga',
            ],
            [
                'company_type' => 'empresa_institucional',
                'name' => 'Cooperativa Lechera Metropolitana',
                'nit' => '900000010',
                'email' => 'compras@clemet.bo',
                'phone' => '70010010',
                'address' => 'Av. Montes 800',
                'city' => 'La Paz',
                'owner_first_name' => 'Veronica',
                'owner_last_name_paterno' => 'Ortega',
                'owner_last_name_materno' => 'Perez',
            ],
            [
                'company_type' => 'tienda_barrio',
                'name' => 'Tienda Las Lomas',
                'nit' => '900000011',
                'email' => 'lomas@barrio.bo',
                'phone' => '70010011',
                'address' => 'C. 1 Las Lomas',
                'city' => 'La Paz',
                'owner_first_name' => 'Julia',
                'owner_last_name_paterno' => 'Vargas',
                'owner_last_name_materno' => 'Linares',
            ],
            [
                'company_type' => 'tienda_barrio',
                'name' => 'Minimarket El Puente',
                'nit' => '900000012',
                'email' => 'puente@minimarket.bo',
                'phone' => '70010012',
                'address' => 'Av. Panoramica 77',
                'city' => 'El Alto',
                'owner_first_name' => 'Hugo',
                'owner_last_name_paterno' => 'Lopez',
                'owner_last_name_materno' => 'Duran',
            ],
            [
                'company_type' => 'tienda_barrio',
                'name' => 'Bodega Santa Rosa',
                'nit' => '900000013',
                'email' => 'santarosa@bodega.bo',
                'phone' => '70010013',
                'address' => 'C. Kollasuyo 30',
                'city' => 'La Paz',
                'owner_first_name' => 'Rene',
                'owner_last_name_paterno' => 'Gutierrez',
                'owner_last_name_materno' => 'Mamani',
            ],
            [
                'company_type' => 'tienda_barrio',
                'name' => 'Kiosko Central',
                'nit' => '900000014',
                'email' => 'kiosko@central.bo',
                'phone' => '70010014',
                'address' => 'Plaza Central puesto 4',
                'city' => 'El Alto',
                'owner_first_name' => 'Sofia',
                'owner_last_name_paterno' => 'Arana',
                'owner_last_name_materno' => 'Pinto',
            ],
            [
                'company_type' => 'tienda_barrio',
                'name' => 'Market Estrella',
                'nit' => '900000015',
                'email' => 'estrella@market.bo',
                'phone' => '70010015',
                'address' => 'Av. Montreal 17',
                'city' => 'La Paz',
                'owner_first_name' => 'Patricia',
                'owner_last_name_paterno' => 'Rivas',
                'owner_last_name_materno' => 'Cardenas',
            ],
            [
                'company_type' => 'tienda_barrio',
                'name' => 'Super Ahorro Barrio',
                'nit' => '900000016',
                'email' => 'ahorro@barrio.bo',
                'phone' => '70010016',
                'address' => 'Av. Juan Pablo II 500',
                'city' => 'El Alto',
                'owner_first_name' => 'Adrian',
                'owner_last_name_paterno' => 'Campos',
                'owner_last_name_materno' => 'Yujra',
            ],
            [
                'company_type' => 'tienda_barrio',
                'name' => 'Almacen San Pedro',
                'nit' => '900000017',
                'email' => 'sanpedro@almacen.bo',
                'phone' => '70010017',
                'address' => 'Barrio San Pedro 45',
                'city' => 'La Paz',
                'owner_first_name' => 'Teresa',
                'owner_last_name_paterno' => 'Flores',
                'owner_last_name_materno' => 'Callisaya',
            ],
            [
                'company_type' => 'tienda_barrio',
                'name' => 'Tienda El Trigal',
                'nit' => '900000018',
                'email' => 'trigal@tienda.bo',
                'phone' => '70010018',
                'address' => 'C. Trigal 12',
                'city' => 'La Paz',
                'owner_first_name' => 'Daniel',
                'owner_last_name_paterno' => 'Romo',
                'owner_last_name_materno' => 'Beltran',
            ],
            [
                'company_type' => 'tienda_barrio',
                'name' => 'Mini Super Aroma',
                'nit' => '900000019',
                'email' => 'aroma@minisuper.bo',
                'phone' => '70010019',
                'address' => 'Av. Aroma 88',
                'city' => 'El Alto',
                'owner_first_name' => 'Luisa',
                'owner_last_name_paterno' => 'Paz',
                'owner_last_name_materno' => 'Siles',
            ],
            [
                'company_type' => 'tienda_barrio',
                'name' => 'Despensa El Milagro',
                'nit' => '900000020',
                'email' => 'milagro@despensa.bo',
                'phone' => '70010020',
                'address' => 'Zona Sur calle 8',
                'city' => 'La Paz',
                'owner_first_name' => 'Nestor',
                'owner_last_name_paterno' => 'Chavez',
                'owner_last_name_materno' => 'Alarcon',
            ],
        ];

        foreach ($companies as $company) {
            Company::updateOrCreate(
                ['nit' => $company['nit']],
                $company + ['created_by' => $creatorId]
            );
        }
    }
}
